baseURL = 'https://harpocoin.xyz/'
languageCode = 'en-us'
title = 'Harpo'

theme = "hugo-theme-learn"

[params]
themeVariant = "blue"
showVisitedLinks = true
disableLandingPageButton = true

[outputs]
home = [ "HTML", "RSS", "JSON"]
